"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./Footer";
import { UserContextProvider } from "./context/UserContext";

import { AntdRegistry } from '@ant-design/nextjs-registry';

import {
  useQuery,
  useMutation,
  useQueryClient,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import { RoomContextProvider } from "./context/roomContext";
import { ChatRoomContextProvider } from "./context/cahtRoomContext";
import { AuthProvider } from "./context/authContext";
import { MenuProvider } from "./context/menuContext";
import Head from "next/head";

const queryClient = new QueryClient()

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "wazacom-server",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Head>
        <title>agiza-server</title>
        <meta property="og:title" content="afiza" key="agiza"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <QueryClientProvider client={queryClient}>
          <UserContextProvider>
            <RoomContextProvider>
              <ChatRoomContextProvider>
                <AntdRegistry>
                  <AuthProvider>
                    <MenuProvider>
                    {children}
                    </MenuProvider>
                  </AuthProvider>
                </AntdRegistry>
            </ChatRoomContextProvider>
            </RoomContextProvider>
          </UserContextProvider>
        </QueryClientProvider>

        <Footer />
      </body>
    </html>
  );
}
